name: Style Dictionary Workflow

run-name: ${{ github.actor }} is building tokens via style dictionary and publishing package

on:
  push:
    tags:
      - v0.**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --immutable --immutable-cache --check-cache
      - name: Build package
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN }}
